core/primitives.go
internal/e2etest/split_test.go
model/writer.go

Update page resources Font dictionary when applying license information

---

core/parser.go

Fixes reading all files attached in issue #59 except one which is failing due to another issue.

Fix parsing names with containing the # character

---

core/parser.go

Resolves #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/80)

Consider files not encrypted when Encrypt object is null

---

common/license/key.go
common/version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/82)

License handling, expiry

---

core/parser.go

Resolves #62 and the file that passes ghostscript validation of issue #63 (376614.pdf)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/89)

Handle improper usage of the array ending marker

---

model/fields.go

Addresses #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/90)

Skip invalid Metadata stream in form field Kids array

---

model/writer.go

Addresses #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/97)

Resolve page Resources references on writer page add, if page reader is lazy

---

Jenkinsfile
internal/e2etest/fdfmerge_test.go

Manually verified that output PDFs look good and leave hash check to detect change. If there is a change in the future, the hash change will trigger a failure upon which the output PDFs need to be re-checked and hashes updated if appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/98)

FDF form filling and flattening e2e test cases

---

internal/e2etest/fdfmerge_test.go
model/flatten.go
model/page.go

Addresses #92
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/93)

Fix annotation flatten when AcroForm does not exist

---

Gopkg.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/100)

Update go dep file

---

Gopkg.lock
Jenkinsfile
common/version.go
core/parser.go
internal/e2etest/fdfmerge_test.go
model/fields.go
model/flatten.go
model/outlines.go
model/page.go
model/reader.go
model/writer.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/102)

Prepare release v3.0.3

---

creator/creator.go

Addresses #105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/106)

Allow adding an external outline tree to the creator

---

model/writer.go

Addresses #108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/115)

Resolve references when adding page to writer from a lazy reader

---

Jenkinsfile

Add UNIDOC_JBIG2_TESTDATA environment variable pointing to testdata directory
- Needed to be able to run tests in PR #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/120)

Add UNIDOC_JBIG2_TESTDATA  to Jenkinsfile

---

internal/jbig2/segments/text-region.go
internal/jbig2/tests/bench_test.go
internal/jbig2/tests/common_test.go
internal/jbig2/tests/document_decode_test.go
internal/jbig2/tests/goldens_test.go

This PR contains JBIG2 Decoder benchmark fixes, for the latest changes. It also contains some minor documentation and a text region panic prevent patches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/121)

JBIG2 Decoder benchmark patch

---

model/form.go

Addresses #125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/128)

Add option to generate appearance dicts when filling form fields

---

README.md
common/version.go

Updates README and version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/132)

Merge master into development

---

creator/creator.go
creator/creator_test.go

Addresses #18
Benchmarks on my computer:
development branch:
```
BenchmarkParagraphAdding:
2000	711058    ns/op
300     4328161   ns/op
20      90405041  ns/op
```
creator-draw optimize branch:
```
BenchmarkParagraphAdding:
2000	621775   ns/op
2000	792756   ns/op
500	2860231  ns/op
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/136)

Creator optimize drawing blocks

---

creator/block.go
creator/creator_test.go

Addresses #56 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/133)

Inherit rotation when creating block from page using the creator

---

README.md
common/version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/141)

Merge master into development following v3.1.1 release

---

Jenkinsfile
internal/e2etest/extract_images_test.go
internal/e2etest/fdfmerge_test.go
internal/e2etest/memory_measure.go
internal/e2etest/split_test.go

Related to #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/146)

Add extract images test case, with memory profiling

---

creator/creator.go

Addresses #150, #151 and #155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/156)

Fix drawing creator pages with no rendered blocks

---

.travis/build_examples.sh
Jenkinsfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/166)

Adapt CI config files

---

model/reader.go

Resolves #170
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/172)

Prevent recursion when parsing outlines

---

creator/table.go

Addresses #154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/173)

Fix TOC page numbering for chapters containing tables

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/186)

Update pricing link

---

extractor/text.go

Addresses #192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/196)

Prevent extractor panic for invalid PDF text objects

---

creator/creator.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/198)

Make the Finalize method of the creator public

---

internal/textencoding/utf16.go
model/font_composite.go

Related to #200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/203)

Add basic support for UTF-16 text encodings

---

render/image_device.go
render/renderer.go

Resolves #210
Resolves the content offset and cropping issues described by #211. The sample is still affected by #209 in that the character spacing is incorrect, and it will be resolved as part of that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/214)

Apply crop box and account for media box offset.

---

model/reader.go

Resolves #213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/215)

Prevent recursive parsing of invalid circular outlines

---

render/context/text_font.go
render/context/text_state.go

Fixes spacing issues of #209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/217)

Improve metrics of rendered characters

---

common/version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/219)

Merge release/v3.3.1 into development

---

core/crypt.go

Addresses #222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/225)

Attempt decryption for invalid crypt filter dictionary type

---

model/reader.go

Also addresses #226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/228)

Improve traversal of outline item nodes in the GetOutlinesFlattened method

---

model/outline.go
model/outlines.go
model/outlines_test.go
model/reader.go

Addresses #227
**Usage**
Extract outline.
```go
outline, err := reader.GetOutlines()
if err != nil {
log.Fatal(err)
}
```
JSON marshal
```go
buf, err := json.Marshal(outline)
if err != nil {
log.Fatal(err)
}
```
JSON unmarshal
```go
outline = model.NewOutline()
if err := json.Unmarshal(buf, outline); err != nil {
log.Fatal(err)
}
```
Apply outline
```go
writer := model.NewPdfWriter()
writer.AddOutlineTree(outline.ToOutlineTree())
```
JSON sample
```json
{
"entries": [
{
"title": "C1",
"dest": {
"page": 0,
"x": 0,
"y": 0
},
"entries": [
{
"title": "Sheets and Views",
"dest": {
"page": 0,
"x": 0,
"y": 0
},
"entries": [
{
"title": "SITE PLAN",
"dest": {
"page": 0,
"x": 0,
"y": 0
},
"entries": null
}
]
}
]
},
{
"title": "A1",
"dest": {
"page": 0,
"x": 0,
"y": 0
},
"entries": [
{
"title": …
```

Improve outline extraction

---

core/parser.go

Addresses #230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/232)

Extend buffer used for searching EOF marker

---

model/outline.go
model/outlines_test.go
model/reader.go

Related to #227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/233)

Improve outline destination parsing

---

core/parser.go

Related to #230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/238)

Add tolerance for seeking EOF marker between read data buffers

---

common/version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/250)

Merge release v3.4.0 into development

---

.github/workflows/greetings.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/253)

Greeting workflow

---

internal/cmap/cmap.go
internal/textencoding/cmap.go
model/font.go
model/font_test.go

Related to https://github.com/unidoc/unipdf-examples/issues/75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/257)

Add PdfFont text encoding methods

---

model/font_composite.go

Addresses #271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/272)

Add basic glyph metrics support for Type 0 CID fonts

---

model/internal/fonts/ttfparser.go

Addresses #268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/273)

Parse TTF encoding subtable 31 after subtable 10

---

.github/workflows/greetings.yml

Copy change from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/278)

Update workflow in development

---

contentstream/processor.go
model/functions.go

Resolves https://github.com/unidoc/unipdf/issues/289 and https://github.com/unidoc/unipdf/issues/290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/291)

Prevent crashing when processing content stream

---

.travis.yml
.travis/cross_build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/298)

Add Travis cross build test

---

core/security/crypt/filter_aesv2.go
core/security/crypt/filter_aesv3.go
core/security/crypt/filter_v2.go
core/security/ecb.go
core/security/standard_r6.go
core/security/standard_r6_test.go
extractor/text.go
internal/textencoding/differences.go
model/internal/fonts/ttfparser.go
render/internal/context/imagerender/path.go

- Remove triggered panics where possible.
- Prevent some unexpected panics.
Related to https://github.com/unidoc/unipdf/issues/302 and https://github.com/unidoc/unipdf/issues/304.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/305)

Prevent panics

---

model/functions.go

Related to https://github.com/unidoc/unipdf/issues/307.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/309)

Prevent Type 0 function evaluation crash

---

contentstream/creator.go
contentstream/operand_list.go
extractor/text.go
render/internal/context/text_state.go
render/renderer.go

Resolves https://github.com/unidoc/unipdf/issues/287 and https://github.com/unidoc/unipdf/issues/310.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/313)

Double quote content stream operator fixes

---

internal/ccittfax/encoder.go

Resolves #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/315)

Fix for crash in CCITT decoder.  Resolves #314.

---

internal/cmap/cmap.go

Related to https://github.com/unidoc/unipdf/issues/318.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/324)

Cache raw CMap data

---

go.mod
go.sum
model/appender_test.go
model/sighandler/sighandler_pkcs7.go
model/sighandler/sighandler_timestamp.go
model/signature_handler.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/301)

Add timestamp signature handler

---

creator/creator.go
creator/creator_test.go
model/reader.go
model/writer.go

Related to https://github.com/unidoc/unipdf/issues/323.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/325)

Add low level PageLabels support

---

creator/invoice.go
creator/invoice_test.go

- Add configurable address section headings
- Add Street2 and State fields
- Add configurable address component separator
- Update invoice test cases
Related to https://github.com/unidoc/unipdf/issues/332 and https://github.com/unidoc/unipdf/issues/333.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/334)

Invoice component improvements

---

creator/invoice.go
creator/invoice_test.go

Addresses https://github.com/unidoc/unipdf/issues/339.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/342)

Fix incorrect render of invoice totals

---

internal/cmap/cmap.go
model/font_composite.go

Related to https://github.com/unidoc/unipdf/issues/322.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/344)

Fix CMap generation and serialization for composite fonts

---

creator/table.go
creator/table_test.go

Addresses https://github.com/unidoc/unipdf/issues/347.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/348)

Fix table right-aligned content

---

model/annotations.go
model/form_test.go
model/reader.go

- Add reader AcroForm repair method 
- Add method for retrieving widget annotation form field
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/351)

Add reader AcroForm repair functionality

---

model/form_test.go
model/reader.go

- Add AcroForm repair check method
- Add AcroForm repair check test case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/356)

Add reader method for checking if the AcroForm needs repair

---

creator/creator.go
creator/creator_test.go
model/outline.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/359)

Use page indirect object for internal outline destinations

---

extractor/text.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/349)

Account for parent CTM when calculating positions of extracted forms

---

annotator/field_appearance.go

Related to #352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/364)

Account for rotation when generating flattened text field appearances

---

common/logging.go
extractor/text.go
extractor/text_test.go
internal/cmap/cmap.go
internal/cmap/cmap_parser.go
internal/cmap/cmap_test.go
internal/textencoding/cmap.go
internal/textencoding/glyphs_glyphlist.go
model/font.go

Hi Gus,
This is only to show you how I am staring the multibyte CMap entry handling.
Please read the comments in the diff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/353)

Handle multibyte entries in CMaps.

---

model/reader.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/367)

Fix outline null object check

---

creator/creator_test.go
model/writer.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/377)

Skip referenced pages which are not present in the catalog

---

creator/creator_test.go
extractor/text.go
extractor/utils.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/381)

Add fill and stroke colors for extracted text marks

---

Jenkinsfile
annotator/form_fill_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unipdf/387)

Add form fill render tests
